### PR TITLE
Remove duplicate const declaration specifier

### PR DESCRIPTION
**Pull request by nicki-krizek**

### CODE REVIEW

**Comment by nicki-krizek** [comment]
@pemensik Hi, could you please take a look at this PR and ACK?

It's just a typo that was preventing a build on fedora rawhide to due some warnings.

**Review by pemensik — APPROVED** [review]
Of course, after asterisk it would mean something, here it is useless.

**Comment by nicki-krizek** [comment]
Fixed upstream.

master

- f76ca3b3a4c2c030071dd23c706d8cc06e1fa2a9

**Comment by nicki-krizek** [comment]
@pemensik Thanks for review!

**Pull request closed without merging**
