### PR TITLE
releng: remove obsolete Trac scripts

### PR DESCRIPTION
**Pull request by nicki-krizek**
Helper scripts for Trac are no longer necessary, because project was
migrated to pagure.io.

### CODE REVIEW

**Comment by MartinBasti** [comment]
Probably those scripts should be migrated to `libpagure`

**Comment by MartinBasti** [comment]
(if they are usefull for pagure use cases)

**Comment by nicki-krizek** [comment]
The script only adds a version with a proper datetime tag.

Since there are no special fields for versions in Pagure (`fixedin` is text), these script are no longer needed.

[Releases in Pagure](https://pagure.io/bind-dyndb-ldap/releases) are tracked directly from the git tags.

**Comment by MartinBasti** [comment]
Ok then ACK

**Comment by nicki-krizek** [comment]
master:

- f5d6f5e821b4f714e8534742b450f7fdd577f766

**Pull request closed without merging**
